version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: MaterialDesignThemes
    versions:
    - 3.2.0
  - dependency-name: MaterialDesignColors
    versions:
    - 1.2.7
  - dependency-name: MaterialDesignExtensions
    versions:
    - 3.2.0
