//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RarJpeg.NetCore.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RarJpeg.NetCore.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string AcceptButtonContent {
            get {
                return ResourceManager.GetString("AcceptButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive is corrupted or not an archive..
        /// </summary>
        internal static string ArchiveCorrupted {
            get {
                return ResourceManager.GetString("ArchiveCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive doesn&apos;t exist or path string is empty..
        /// </summary>
        internal static string ArchiveExistEmpty {
            get {
                return ResourceManager.GetString("ArchiveExistEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive doesn&apos;t contain extension..
        /// </summary>
        internal static string ArchiveExtension {
            get {
                return ResourceManager.GetString("ArchiveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select archive.
        /// </summary>
        internal static string ArchiveHint {
            get {
                return ResourceManager.GetString("ArchiveHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButtonContent {
            get {
                return ResourceManager.GetString("CancelButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container file doesn&apos;t exist or path string is empty..
        /// </summary>
        internal static string ContainerExistEmpty {
            get {
                return ResourceManager.GetString("ContainerExistEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected container file doesn&apos;t have extension. Continue?.
        /// </summary>
        internal static string ContainerExtension {
            get {
                return ResourceManager.GetString("ContainerExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select container file.
        /// </summary>
        internal static string ContainerHint {
            get {
                return ResourceManager.GetString("ContainerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        internal static string CopyToClipboardToolTip {
            get {
                return ResourceManager.GetString("CopyToClipboardToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file&apos;s path is empty..
        /// </summary>
        internal static string OutputEmpty {
            get {
                return ResourceManager.GetString("OutputEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file is already exists..
        /// </summary>
        internal static string OutputExist {
            get {
                return ResourceManager.GetString("OutputExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file contain extension. Please, enter file&apos;s name without extension..
        /// </summary>
        internal static string OutputExtension {
            get {
                return ResourceManager.GetString("OutputExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select output file&apos;s path.
        /// </summary>
        internal static string OutputHint {
            get {
                return ResourceManager.GetString("OutputHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
    }
}
